#vertical RECTANGEl USING *
for i in range(6):
    for j in range(4):
        print("*",end=" ")
    print()
print()
# horizantle rectangl using *
for i in range (5):
    for j in range(8):
        print("*",end=" ")
    print()
print()    
# printing i values
for i in range(6):
    for j in range(4):
        print(i,end=" ")
    print()
print()    
# printing j values
for i in range(6):
    for j in range(4):
        print(j,end=" ")
    print()
print()
# horizantle rectangl using i values
for i in range (5):
    for j in range(8):
        print(i,end=" ")
    print()
print() 
# horizantle rectangl using j values
for i in range (5):
    for j in range(8):
        print(j,end=" ")
    print()
print() 
#vertical RECTANGEl USING A
for i in range(6):
    for j in range(4):
        print("A",end=" ")
    print()
print()
#vertical RECTANGEl USING ram
for i in range(6):
    for j in range(4):
        print("ram",end=" ")
    print()
print()
# horizantle rectangl using Z
for i in range (5):
    for j in range(8):
        print("Z",end=" ")
    print()
print() 
# horizantle rectangl using $
for i in range (5):
    for j in range(8):
        print("$",end=" ")
    print()
print() 